# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 487ba02b0a1f633a6f4623152d8d717a403c1316e60380426b7bea97f4c1ced52ffbe217e2a7573a787e7fca764b2f45764382c8f4ccc098508d6944aa0b307b

test:
  secret_key_base: 03bbbe373d17bd81bdfeed37f2807e4d3dcd97904969767fdf49c0e6684c2346a239293792f383df06714c12af96b44c462dfb610fc9993dbc2330ac4bb96a3e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
